### PR TITLE
Fix `kustomize build` sample

### LINKED ISSUE #36: Example configuration doesn't work with kustomize
Hi,
Running "kustomize build" on example configuration don't work since it uses "../rbac" and "../manager" while kustomize (2.0.1) assumes that it is under the folder which contains the kustomization.yaml, the error is:

> Error: rawResources failed to read Resources: Load from path ../manager/manager.yaml failed: security; file '../manager/manager.yaml' is not in or below '/home/wave-master/config/default'

I moved both folder under default and modify the path accordingly.
Thanks

### PR DESCRIPTION
**Pull request by meganwalker-ibm**
Fixes #36 
These changes makes `kustomize build config/default` work again with current kustomize versions.

I'm not familiar enough with kustomize to know if this is a best-practise solution.... but it works for me locally.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Hi, could you please rebase this on top of our master branch so that we can run the new CI tasks against it?

**Comment by meganwalker-ibm** [comment]
Done.

**Comment by JoelSpeed** [comment]
That was quick! Thanks 😄 
/ok-to-test

**Comment by JoelSpeed** [comment]
Looks like a test flaked, need to sort those out at some point 🙈 
/retest

**Comment by JoelSpeed** [comment]
Thanks for the fix @meganwalker-ibm 😄

**Pull request merged**
