### PR TITLE
Helm chart

### PR DESCRIPTION
**Pull request by marcostvz**
Helm chart proposal, to solve https://github.com/pusher/wave/issues/69

Let me know if you prefer it in a different folder.

### CODE REVIEW

**Comment by marcostvz** [comment]
> do you think this is something we could propose to the upstream charts repository rather than keeping it here?

I believe it makes sense, yes. :) It will also give visibility to your project.

**Comment by marcostvz** [comment]
Hey @JoelSpeed , I added a PR into the helm/incubator, I thought it made more sense as I believe it needs more testing before going into helm/stable.

https://github.com/helm/charts/pull/17866

**Comment by marcostvz** [comment]
Also, please note that I added you and I as approvers/reviewers. If you want to remove me, glad to not be there haha, or if you want more people to be involved.
https://github.com/helm/charts/pull/17866/files#diff-8b411be2d6d255adb8adacb57c2c949b

**Comment by JoelSpeed** [comment]
@marcostvz That sounds fantastic, thank you so much for your contribution. Let's see how the other PR goes and come back to this once there is a decision

**Comment by marcostvz** [comment]
Hey @JoelSpeed , despite the [PR](https://github.com/helm/charts/pull/17866) is alright, the people from helm charts do not want to host new charts and are encouraging to move to [helm hub](https://github.com/helm/hub/blob/master/Repositories.md). Before doing so, this chart should we available in some repository, they suggest [using GitHub pages](https://github.com/helm/hub/blob/master/docs/github.md#github-pages-as-a-repository), but at the moment I do not have time to dedicate to move that forward.

**Pull request merged**
