### PR TITLE
Use image entrypoint for manager container definition

### PR DESCRIPTION
**Pull request by zerok**
Currently, the container definition still refers to the `/bin/manager` command which got replaced with `/bin/wave` in 8f5edec223de1a90268fdfa0e6de5762f745bca0 🙂

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/ok-to-test

This looks reasonable, will have to run the tests and get merged, thanks for the PR!

**Comment by zerok** [comment]
@JoelSpeed : Is there something I can do to help fixing the build errors? 

```
 grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export sigs.k8s.io/controller-runtime: fatal: failed to unpack tree object 7f16f2b744937bb10e5a3acca56aa5b54f534813 
```

**Comment by JoelSpeed** [comment]
@zerok I'm a bit confused as to why this has suddenly failed, I'm working on a fix today though, hold tight!

**Comment by zerok** [comment]
@JoelSpeed Awesome! Thank you 😄

**Comment by zerok** [comment]
Thank you!

**Pull request merged**
